server:
  port: 8080

spring:
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
    virtual-host: /
    connection-timeout: 60000
    publisher-confirms: true #确认消息已发送到交换机ack
    publisher-returns: true #确认消息已发送到队列ack
    cache:
      channel:
        size: 1
    listener:
      simple:
        acknowledge-mode: manual
  redis:
    host: 127.0.0.1
    port: 6379
    password: xwbing
    timeout: 30s
    jedis:
      pool:
        max-active: 50 #连接池最大连接数
        max-wait: -1 #连接池最大阻塞等待时间（使用负值表示没有限制）
        max-idle: 5 #连接池最大空闲连接
        min-idle: 0 #连接池最小空闲连接

xxl:
  job:
    admin-addresses: http://127.0.0.1:7777/xxl-job-admin
    access-token: SEC9f4390e8c897e
    executor-ip:
    executor-port: 8001
    executor-log-retention-days: 3

boot:
  redis:
    host: 127.0.0.1
    port: 6379
    password: xwbing
    timeout: 10000
    pool:
      max-total: 50
      max-idle: 5
      min-idle: 0
  aliyun:
    log:
      log-store: test_boot
    ons:
      access-id: xx
      access-secret: xx
      name-server-address: xx
      producer-group-id: xx
    oss:
      endpoint: https://oss-cn-hangzhou.aliyuncs.com
      region: oss-cn-hangzhou
      region-id: cn-hangzhou
      access-id: xx
      access-secret: xx
      bucket: moo-oss-test
      sts-roleArn: xx
      sts-role-session-name: xx

swagger:
  enable: true