server:
  port: 8080

spring:
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
    virtual-host: /
    connection-timeout: 60000
    publisher-confirms: true #确认消息已发送到交换机ack
    publisher-returns: true #确认消息已发送到队列ack
    cache:
      channel:
        size: 1
    listener:
      simple:
        acknowledge-mode: manual #手动确认消费ack

xxl:
  job:
    admin-addresses: http://127.0.0.1:7777/xxl-job-admin
    access-token: SEC9f4390e8c897e
    executor-ip:
    executor-port: 8001
    executor-log-retention-days: 3

boot:
  redis:
    host: 127.0.0.1
    port: 6379
    password: xwbing
    timeout: 10000
    maxTotal: 50
    maxIdle: 5
    minIdle: 0
  aliYun:
    log:
      log-store: test_boot
    ding-talk:
      web-hook: https://oapi.dingtalk.com/robot/send?access_token=da82d4099a3f2515480f35210cc17dd02f315e99537d29cd3de1a751e551b670
      secret: SECa17df9ae897fb39d525a173c47dcc93a6b01133fbb4bf3e659060cd4ed4539ea
    ons:
      username: xx
      password: xx
      nameServerAddress: xx
      producerGroupId: xx
swagger:
  enable: true

aliPay:
  payGateWay: XX