server:
  port: 8081

spring:
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
    virtual-host: /
    connection-timeout: 60000 #毫秒
    publisher-confirms: true #支持发布确认（确认消息是否发送到交换器）
    publisher-returns: true #支持发布返回（确认消息没有存入到相应的队列）
    cache:
      channel:
        size: 1
    listener:
      simple:
        acknowledge-mode: manual #消息接收手动ack确认

xxl:
  job:
    admin-addresses: http://127.0.0.1:7777/xxl-job-admin
    access-token: SEC9f4390e8c897e
    executor-ip:
    executor-port: 8002
    executor-log-retention-days: 7

#自定义自动配置参数
boot:
  redis:
    host: 127.0.0.1
    port: 6379
    password: xwbing
    timeout: 10000
    pool:
      max-total: 100
      max-idle: 10
      min-idle: 0
  aliyun:
    log:
      log-store: prod_boot
  host: 127.0.0.1
  appHost: 127.0.0.1
  rsa:
    private-key-base64: MIICdQIBADANBgkqhkiG9w0BAQEFAASCAl8wggJbAgEAAoGBALMjTM07sMmuEfXEhvCkyJcWpfiYWrYcbm4bEz4jBjuSJetzgFfHkq/L7p9OaYpEQ9g1yar4GPoLKZzQ5s1GVl4P+RiPDOSJVBrAFTn4Ezg9l7z4kAeq01/knhEiP2+MphhJvvLEA8daNwLD8QIkDEeqj77BYXF9W2+FD86GMtmTAgMBAAECgYARuqx8YsF4RxQ7oi6GvOWmCmr1Dm2/41LMmT0PeRuXTrtrsPE3/tEA5BU4SrmS98xNJuRQLvYYh9Kfqg8wVsXvphm8frAFKUsJnVbSxZFIKF/XShTxaaA3Nhnw+4xLMcBeCx2sp9fHjpURPDzmpHNwPfswuCEnt696ZNImFnYmCQJBAPgoh6+Tfqz+inHWX4Kngg2oaXDxALf9x5suQxSWQp4zeU8s0S1z4eFAC0RPvyG7gcDoWd5cjTnhZ5TxnJcCOEsCQQC4zG5cU3Rs5mCvX6dquq3x/tnJCa9JO4/XWm+XnMrjviOezDYyVzeBxJRDLam0pQmccwmiyfU4vXXCv0HFIibZAkBN+t54a87YqbvzfbvRoLWbeRp5JSJmrta0itsFcxpIAEDUgm7Q66NFVwyzUKPtA7EIX3suBsNSNuSHx0y/nzD1AkAmYH4CumoRO36UrP6tkXsSKGS99T7rrGzgwi0uhSc1SIVJMwuGRMqILnTDxrXZh/SJAvLbVamRUPclrGZSNBdxAkAfbInSL9qd2WTEnYavTQzQA++A939VurcOp1UIHf/j5YbhWP2CAX7RPoyjMJncrKZCKZj8lTqWmero2JgAuRx0
    public-key-base64: MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQCzI0zNO7DJrhH1xIbwpMiXFqX4mFq2HG5uGxM+IwY7kiXrc4BXx5Kvy+6fTmmKREPYNcmq+Bj6Cymc0ObNRlZeD/kYjwzkiVQawBU5+BM4PZe8+JAHqtNf5J4RIj9vjKYYSb7yxAPHWjcCw/ECJAxHqo++wWFxfVtvhQ/OhjLZkwIDAQAB

swagger:
  enable: false

alipay:
  pay-gate-way: XX


