server:
  port: 8080

spring:
#  rabbitmq:
#    host: 127.0.0.1
#    port: 5672
#    username: guest
#    password: guest
#    virtual-host: /
#    connection-timeout: 60000
#    publisher-confirms: true #确认消息已发送到交换机ack
#    publisher-returns: true #确认消息已发送到队列ack
#    cache:
#      channel:
#        size: 1
#    listener:
#      simple:
#        acknowledge-mode: manual
  redis:
    host: 127.0.0.1
    port: 6379
    password: xwbing
    timeout: 30s
    jedis:
      pool:
        max-active: 50 #连接池最大连接数
        max-wait: -1 #连接池最大阻塞等待时间（使用负值表示没有限制）
        max-idle: 5 #连接池最大空闲连接
        min-idle: 0 #连接池最小空闲连接

xxl:
  job:
    admin-addresses: http://127.0.0.1:7777/xxl-job-admin
    access-token: SEC9f4390e8c897e
    executor-ip:
    executor-port: 8001
    executor-log-retention-days: 3

boot:
  redis:
    host: 127.0.0.1
    port: 6379
    password: xwbing
    timeout: 10000
    pool:
      max-total: 50
      max-idle: 5
      min-idle: 0
  aliyun:
    log:
      log-store: test_boot
    ons:
      access-id: xx
      access-secret: xx
      name-server-address: xx
      producer-group-id: xx
    oss:
      endpoint: oss-cn-hangzhou.aliyuncs.com
      region: oss-cn-hangzhou
      region-id: cn-hangzhou
      access-id: xx
      access-secret: xx
      bucket: moo-oss-test
      sts-roleArn: xx
      sts-role-session-name: xx
  wx:
    mp:
     app-id: xx
     secret: xx
     token: xx
     aes-key: xx
    ma:
     app-id: xx
     secret: xx
     token: xx
     aes-key: xx
     msg-data-format: JSON
    open:
      app:
        configs:
          ## 移动应用
          - app-id: wxaa53522f91fbf6b4
            secret: 9c81a97bf231df562c4e850ecc2cb334
  yunxin:
    app-key: 499a1a03974e66aa6a86245bd9dc1704
    app-secret: 2ced8a7f7810
  host: http://3f75-60-191-78-7.ngrok.io
  appHost: 127.0.0.1
  rsa:
    private-key-base64: MIICdgIBADANBgkqhkiG9w0BAQEFAASCAmAwggJcAgEAAoGBANQMypvo6mbfpBQ5nlA2G+2DooGXqUKxBAJ8fHsnX3SFCRZ72q1ix3Gh2geI/b5uNZdvsqB24cIyh/cg9RSfPyPakoap25TpR61FI/4kAVvW5vqcZSf1wsBQYtzMvyzbSbqFDbg7dmqzEIouxDumUj6cAM1LYVb2cwqzrAaYfqi/AgMBAAECgYAL7xMGsUC353A23y3vZQwvUtA2K5CQEKGheNtnRvD9VXC3KONGt3TICrbYOQ0mxtG8oxb80ZP6YkOlVIqBIvE3phF9TlfcoKkC3SMA6MEHYZMmpfgitpXJc23hu11IHg/0RFFvrGL8hSZSlRYsNdrabO6GpO4xRD4WoEqSwaQRiQJBAPiCdfTRzqdFnyyYNbQ+q5BVI3WmI5gE7UTrvL9qxwCxClcZlqgTGsTMsmyZP2yuG7hWnS0HeBw0yHLcyTtKvH0CQQDacQCXzkVI27SYc3yo6SeF5v0WCKhrfvAuYKwN3GGMwwzvn2hccLzSjxmHZXPWIPVxJRe/b3FXuz+ooU+4HcrrAkBvF1sFu3jnO+9hLxXq4o0tc3HrmP6WabVrtvpkk6Ysf/hAYZcAwbGYwm0MsSEyQ07vBAE1bP5blZj6CAsJL2q9AkAeAgYN1KVJ8/ykMMFARv9J8shzvW69jaubA2a/ZLX161mclW51vHsEBeqA4hv+n3p4N5tCjiGo5q1BEh/scBNPAkEAhK2V5vYAPrJtjvIeYouyXbTHisALS8REJ3vtHHm07q3QKxIGQv+5UPje9EFnczkqM6wur0Bunoq3/HdyeAo/ZA==
    public-key-base64: MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQDUDMqb6Opm36QUOZ5QNhvtg6KBl6lCsQQCfHx7J190hQkWe9qtYsdxodoHiP2+bjWXb7KgduHCMof3IPUUnz8j2pKGqduU6UetRSP+JAFb1ub6nGUn9cLAUGLczL8s20m6hQ24O3ZqsxCKLsQ7plI+nADNS2FW9nMKs6wGmH6ovwIDAQAB

swagger:
  enable: true

alipay:
  server-url: https://openapi.alipaydev.com/gateway.do
  app-id: 2016102100730784
  user-id: 2088102180492575
  app-private-key: MIIEvAIBADANBgkqhkiG9w0BAQEFAASCBKYwggSiAgEAAoIBAQCJ+EmKYCfa+y8L6xpQCQe+6CK/ZFFKcSR82/1Z6eWKnb3Taynt/8Ow63fD6jgKLnAHG1ErFTK2c8nBNhhWj7/cOk8+f6xYW5Egf4cgZWlkY9DBuWP5OhlkXzjblDdFKIKxOwT2Xm+j5FDnlXeEFLKjJNzTzDaSC7ngdAgnj271WiZ81+M7F83fHTsQH6bYr9XVhasNDakSgysp+k3XZYGBgW5NK0daiaYnSrqGlvxPiCiFLY1CzEbG/VnKnMruC9X7Dr7yc9QZhmrhAGZElbZMUb1QPf2eQsHIH+XUk442A4suna+/cm2dAjbmQ9z3QI7GTos9V72jqJgDiybkp88nAgMBAAECggEANKJ+G8Y3LjlpZ1iXvzTSuagBqZZx1L55NxEOBEFRCqLHCmL1qhBK7bHHDPzLyEaTAoMPYipCIIznyUgD3PIWNcQg+yzl6Qd1xDoiqN9HZ78UovNBCpF5omsZW9udgkrEISzs5bh9Sr8NhmvlHoRu6gJkJIDhyLGkhdZ+TelQYVUlcxiEIYqcnaQToOdu0kD7lh0KPuPK7ozY3w0exOHLonDrEEu2HJwgGw5dvjb/TK1f7bCkWzSDkuBjauMMr8uLgsFFVYH4F1WWjAfxVsS7vhW9PZxJzpWF0lb1+VzMoudqO7+SuECcDu6YmTAjTcyVsf9YIBMHf/C6KKCJVxdVMQKBgQDH10nueTgUYBHpBm0CXLVkBOuDK8jns9A4gkrXh1DCjTFHcXxvjSoezjTdknpniBRfBHcgvdgd+oQTPkdJQe4vS4gCYsp2taG2tERspOSdvmcHtNhbd+3YKkPd/S/ZlQiYd9NVhHmSD+qk3T0z5ragFunzStK+bP0qH68zN3gj/QKBgQCwvfHRBaEUZaoYv/cAiajr/32/pVP4/FK/F2+XjJa8vYHg2cVDOnq8s9c2K/1Q0JQoPslypNmhxUlFcyQOP2TSDkWNk2qP0KhAvft25zOULIGuy1y19r8w7HfJLJzMnK3lmJD83w01vhcQNGRDEAHrlkFel+lTJPlZMWySBN4e8wKBgGO6E0H3qj24x5dTRpkULM0yC1mVQxglyrY4hyLRe0LrdPkjMCb2+lsPKqCcFYuPBCN6tfxX4P7s4nY78RUk2rktZz1RkZn2ADKN+UuCajgyKXZWEFZtHftu9BlW3UcmsXhs68DUcFqsqLsHUSCSdPalGLD52PuApkIcN7FGcCT9AoGAdJIDISK+WC6pnsNWDWO+J1GOxc0scmcxyFmTv3f5n6i6NexMIAg9FaLkChW/cQLxBQ5MXbH+3KS7q/PCTydevvCszTDyssIjhvgHGChrq4ojSn9Uuatx9LmyU9x52rZoN6uFzVLsaoriuUxk6JpxOcoTeWlmefFECKEBg9l0CyMCgYAJCDTXZWmju6OeO+I+36b+OzzlbvIwAbHLwjyS5dizfKC5xAWn40mHKh0Z3W5cADpausoCptfJ5h4vBfWJftwbchaZIf43l+THKBI4B8p+DcYjrvSrO0rCZjUPp2/lX2YwJdtKUR+NAyVhWPYL+1kkox3ZJog/Rm1p409YZ6UhEQ==

elasticsearch:
  username: elastic
  password: 8RWTLqfPPrjXnTWoplWylldOS_K9
  hosts:
    - 172.30.37.164:3006

nacos:
  discovery:
    server-addr: 127.0.0.1:8848
#    namespace: 00246e3a-6129-4d67-9012-549b29df5b89
  config:
    server-addr: 127.0.0.1:8848
    data-id: com.ifugle.nami-dev.yaml
    auto-refresh: true
    type: yaml
#    namespace: 00246e3a-6129-4d67-9012-549b29df5b89