#server
server:
  servlet:
    context-path: /
    session:
      timeout: 6h

#spring
spring:
  profiles:
    active: dev
  servlet:
      multipart:
        max-file-size: 10MB
        max-request-size: 100MB
  aop:
    auto: true # Add @EnableAspectJAutoProxy
    proxy-target-class: false
  #编码
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  mail:
    host: smtp.163.com
    port: 465 #设置端口465，因为阿里25端口默认禁用
    username: xwb1ng@163.com
    password: xwbing000111 #邮箱设置里获取的授权码
    default-encoding: utf-8
    properties:
      mail:
        smtp:
          auth: true #授权
          socketFactory: #因为阿里云服务器25端口默认加密，需要改用sl加密465端口发送邮件
            class: javax.net.ssl.SSLSocketFactory #SSL证书Socket工厂(指定Socket工厂)
            port: 465 #设置ssl端口
            fallback: true #当指定的socket工厂创建socket失败时，是否使用默认的socket工厂创建
          starttls: #对纯文本通信协议的扩展。它提供一种方式将纯文本连接升级为加密连接（TLS或SSL），而不是另外使用一个端口作加密通信。
            enable: true
            required: true
  jpa:
    database: mysql
    show-sql: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
        dialect: org.hibernate.dialect.MySQL5Dialect
  #jackson日期返回格式
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8


#mybatis
#mybatis:
#  mapper-locations: #classpath:mapper/**/*.xml
#  type-aliases-package: #com.xwbing.service.domain.entity
#  config-location: # classpath:mybatisConfig.xml

pagehelper:
  helper-dialect: mysql

#log
logging:
  config: classpath:log4j2.xml

#自定义自动配置参数
boot:
  redis:
    prefix: boot_
  #阿里云配置
  aliyun:
    log:
      enabled: true
      access-id: xx
      access-secret: xx
      endpoint: cn-hangzhou.log.aliyuncs.com
      project: boot-api
      topic: boot_moddule
    oss:
      enabled: true

#切面自动配置参数
aspect:
  service-pointcut: execution(public * com.xwbing.service.service.*.*(..))

xxl:
  job:
    enabled: true
    executor-app-name: boot
    executor-log-path: logs/jobhandler

alipay:
  server-url: https://openapi.alipaydev.com/gateway.do
  app-id: 2016102100730784
  user-id: 2088102180492575
  app-cert-public-key-path: /apps/alipay/appCertPublicKey.crt
  alipay-public-cert-path: /apps/alipay/alipayCertPublicKey_RSA2.crt
  alipay-root-cert-path: /apps/alipay/alipayRootCert.crt
  app-private-key: MIIEvAIBADANBgkqhkiG9w0BAQEFAASCBKYwggSiAgEAAoIBAQCJ+EmKYCfa+y8L6xpQCQe+6CK/ZFFKcSR82/1Z6eWKnb3Taynt/8Ow63fD6jgKLnAHG1ErFTK2c8nBNhhWj7/cOk8+f6xYW5Egf4cgZWlkY9DBuWP5OhlkXzjblDdFKIKxOwT2Xm+j5FDnlXeEFLKjJNzTzDaSC7ngdAgnj271WiZ81+M7F83fHTsQH6bYr9XVhasNDakSgysp+k3XZYGBgW5NK0daiaYnSrqGlvxPiCiFLY1CzEbG/VnKnMruC9X7Dr7yc9QZhmrhAGZElbZMUb1QPf2eQsHIH+XUk442A4suna+/cm2dAjbmQ9z3QI7GTos9V72jqJgDiybkp88nAgMBAAECggEANKJ+G8Y3LjlpZ1iXvzTSuagBqZZx1L55NxEOBEFRCqLHCmL1qhBK7bHHDPzLyEaTAoMPYipCIIznyUgD3PIWNcQg+yzl6Qd1xDoiqN9HZ78UovNBCpF5omsZW9udgkrEISzs5bh9Sr8NhmvlHoRu6gJkJIDhyLGkhdZ+TelQYVUlcxiEIYqcnaQToOdu0kD7lh0KPuPK7ozY3w0exOHLonDrEEu2HJwgGw5dvjb/TK1f7bCkWzSDkuBjauMMr8uLgsFFVYH4F1WWjAfxVsS7vhW9PZxJzpWF0lb1+VzMoudqO7+SuECcDu6YmTAjTcyVsf9YIBMHf/C6KKCJVxdVMQKBgQDH10nueTgUYBHpBm0CXLVkBOuDK8jns9A4gkrXh1DCjTFHcXxvjSoezjTdknpniBRfBHcgvdgd+oQTPkdJQe4vS4gCYsp2taG2tERspOSdvmcHtNhbd+3YKkPd/S/ZlQiYd9NVhHmSD+qk3T0z5ragFunzStK+bP0qH68zN3gj/QKBgQCwvfHRBaEUZaoYv/cAiajr/32/pVP4/FK/F2+XjJa8vYHg2cVDOnq8s9c2K/1Q0JQoPslypNmhxUlFcyQOP2TSDkWNk2qP0KhAvft25zOULIGuy1y19r8w7HfJLJzMnK3lmJD83w01vhcQNGRDEAHrlkFel+lTJPlZMWySBN4e8wKBgGO6E0H3qj24x5dTRpkULM0yC1mVQxglyrY4hyLRe0LrdPkjMCb2+lsPKqCcFYuPBCN6tfxX4P7s4nY78RUk2rktZz1RkZn2ADKN+UuCajgyKXZWEFZtHftu9BlW3UcmsXhs68DUcFqsqLsHUSCSdPalGLD52PuApkIcN7FGcCT9AoGAdJIDISK+WC6pnsNWDWO+J1GOxc0scmcxyFmTv3f5n6i6NexMIAg9FaLkChW/cQLxBQ5MXbH+3KS7q/PCTydevvCszTDyssIjhvgHGChrq4ojSn9Uuatx9LmyU9x52rZoN6uFzVLsaoriuUxk6JpxOcoTeWlmefFECKEBg9l0CyMCgYAJCDTXZWmju6OeO+I+36b+OzzlbvIwAbHLwjyS5dizfKC5xAWn40mHKh0Z3W5cADpausoCptfJ5h4vBfWJftwbchaZIf43l+THKBI4B8p+DcYjrvSrO0rCZjUPp2/lX2YwJdtKUR+NAyVhWPYL+1kkox3ZJog/Rm1p409YZ6UhEQ==
